# Generated by Django 3.0.8 on 2022-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='id',
        ),
        migrations.AlterField(
            model_name='credential',
            name='email',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='credential',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='phone_no',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(),
        ),
    ]
