# Generated by Django 3.0.8 on 2022-02-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_auto_20220207_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
