# Generated by Django 3.0.8 on 2022-02-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_auto_20220207_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
